name: CI-compile

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2dev/ps2dev:main
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile build
        run: |
          make clean all

      - name: Upload sample
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: sample
          path: |
            sample/*.elf

      - name: Create release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: |
            sample/*.elf
